library(ggplot2)
library(gridExtra)
setwd("~/Projects/fixpeaks/enriched/")


# creates a row bound df of all samples with columns describing the sample 
makedf <- function(){
  files <- list.files('~/Projects/fixpeaks/sums-peak-by-gene/',full.names = TRUE)
  n <- length(files)
  df <- data.frame(chr = NA, start=NA, end=NA, CNAG=NA, score=NA, strand=NA, condition=NA, replicate=NA, sample=NA, od=NA, tf=NA)
  for (i in 1:n){
    sample          <- strsplit(strsplit(files[i],'//')[[1]][2],'_s')[[1]][1]
    genes           <- read.table(files[i],header=FALSE,sep=" ")
    names(genes)    <- c('chr','start','end','CNAG','score','strand')
    
    if     ( substr(sample,1,1)=='q'){ 
             condition <- 'Mutant'
    } else { condition <- 'WildType' }
    
    if     ( condition=='Mutant'){
             od <- paste('OD',substr(sample,7,7),sep='')
    } else { od <- paste('OD',substr(sample,6,6),sep='')}
    
    if     ( condition=='Mutant'){
             replicate <- substr(sample,3,3)
    } else { replicate <- substr(sample,2,2)}
     
    if     ( condition=='Mutant'){
             letter <- substr(sample,2,2)
    } else { letter <- substr(sample,1,1)}
    if (letter=='C'){ tf <- 'Cqs2'}
    if (letter=='N'){ tf <- 'Nrg1'}
    if (letter=='L'){ tf <- 'Liv3'}
    
    genes$condition <- condition
    genes$replicate <- replicate
    genes$sample    <- sample
    genes$od        <- od
    genes$tf        <- tf
    df              <- rbind(df,genes)
  }
  df <- na.omit(df)
  return(df)
}

# creates a column bound df with scores of different samples in the columns
makedf_rows <- function(){
  
  files     <- list.files('~/Projects/fixpeaks/sums-peak-by-gene/',full.names = TRUE)
  n         <- length(files)
  df        <- read.table(files[1],header=FALSE,sep=" ")
  names(df) <- c('chr','start','end','CNAG','score','strand')
  df$score  <- NULL
  
  for (i in 1:n){
    
    sample       <- strsplit(strsplit(files[i],'//')[[1]][2],'_s')[[1]][1]
    genes        <- read.table(files[i],header=FALSE,sep=" ")
    names(genes) <- c('chr','start','end','CNAG','score','strand')
    
    df <- cbind(df,genes$score)
    names(df)[i+5] <- sample
  }
  df <- na.omit(df)
  return(df)
}

# ggplot function
plotr <- function(df,rep1,rep2,rsq){
  if(grepl('OD1',rep1)){ OD='OD1'} else { OD='OD5'}
  if(grepl('q',rep1))  {condition='Mutant'} else { condition='Wild Type'}
  if(grepl('C',rep1)) {tf='Cqs2'} else if(grepl('N',rep1)){tf='Nrg1'} else {tf='Liv3'}
  
  p <- ggplot(df,aes(x=eval(parse(text=rep1)), y=eval(parse(text=rep2))) ) +
    geom_point(alpha=0.18, aes(x=eval(parse(text=rep1)), y=eval(parse(text=rep2))), show.legend = FALSE) + 
    geom_abline(slope=1,intercept=0,col="grey") +
    labs( title=paste(tf,OD,condition),
          subtitle=paste('R-squared: ',round(rsq,4)), x=rep1, y=rep2) +
    scale_x_log10( limits=c(1000,80000)) + 
    scale_y_log10( limits=c(1000,80000)) +
    coord_fixed()
    
  return(p)
}

# generates one plot for rep1 vs rep2
plot_replicates <- function(rep1,rep2){
  df <- makedf_rows()
  rsq <- summary(lm( df[,names(df)==rep1] ~ df[,names(df)==rep2]))$r.squared
  plotr(df,rep1,rep2,rsq)
}

# plots all replicates generated by plot_replicates in a grid
plot_all_replicates <- function(){
  samples <- names(df)[6:29]
  i1 <- sort(c(seq(1,24,by=4),seq(2,24,by=4)))
  i2 <- sort(c(seq(3,24,by=4),seq(4,24,by=4)))
  rep1 <- samples[i1]
  rep2 <- samples[i2]
  
  n <- length(rep1)
  rep_plots <- list()
  for(i in 1:n){
    rep_plots[[i]] <- plot_replicates(rep1[i],rep2[i])
  }
  
  grid.arrange(
    rep_plots[[1 ]],rep_plots[[3 ]],rep_plots[[5 ]],
    rep_plots[[7 ]],rep_plots[[9 ]],rep_plots[[11]],
    rep_plots[[2 ]],rep_plots[[4 ]],rep_plots[[6 ]],
    rep_plots[[8 ]],rep_plots[[10]],rep_plots[[12]],
    ncol=3,nrow=4,
    widths = c(1,1,1),
    top = 'Replicate Scores have High Correlation',
    left ="Replicate1",
    bottom="Replicate2"
  )
}


plot_all_replicates()

